//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trelloyetmezmi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trelloEntities1 : DbContext
    {
        public trelloEntities1()
            : base("name=trelloEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gorevler> gorevler { get; set; }
        public virtual DbSet<gorevler2> gorevler2 { get; set; }
        public virtual DbSet<gorevler3> gorevler3 { get; set; }
        public virtual DbSet<gorevler4> gorevler4 { get; set; }
        public virtual DbSet<gorevler5> gorevler5 { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<stun> stun { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
    }
}
