//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trelloyetmezmi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int tableID { get; set; }
        public string metinID { get; set; }
        public Nullable<int> yerID { get; set; }
    }
}
